import type { ShapeFretLocation } from '@/types/ShapeFretLocation';
export const cagedPositions: ShapeFretLocation[] = [
  { string: 1, fret: 3, color: 'red' },
  { string: 2, fret: 1, color: 'red' },
  { string: 2, fret: 4, color: 'red' },
  { string: 2, fret: 5, color: 'red' },
  { string: 3, fret: 2, color: 'red' },
  { string: 4, fret: 3, color: 'red' },
  { string: 5, fret: 1, color: 'red' },
  { string: 1, fret: 5, color: 'blue' },
  { string: 2, fret: 6, color: 'blue' },
  { string: 3, fret: 5, color: 'blue' },
  { string: 4, fret: 7, color: 'blue' },
  { string: 5, fret: 7, color: 'blue' },
  { string: 1, fret: 8, color: 'cyan' },
  { string: 2, fret: 8, color: 'cyan' },
  { string: 3, fret: 7, color: 'cyan' },
  { string: 2, fret: 9, color: 'cyan' },
  { string: 4, fret: 10, color: 'cyan' },
  { string: 5, fret: 10, color: 'cyan' },
  { string: 6, fret: 8, color: 'cyan' },
  { string: 1, fret: 11, color: 'green' },
  { string: 1, fret: 12, color: 'green' },
  { string: 2, fret: 13, color: 'green' },
  { string: 3, fret: 12, color: 'green' },
  { string: 4, fret: 14, color: 'green' },
  { string: 5, fret: 15, color: 'green' },
  { string: 6, fret: 15, color: 'green' },
  { string: 1, fret: 15, color: 'yellow' },
  { string: 2, fret: 17, color: 'yellow' },
  { string: 3, fret: 17, color: 'yellow' },
  { string: 4, fret: 15, color: 'yellow' },
  { string: 5, fret: 17, color: 'yellow' },
];
